### ISSUE TITLE
No quotes for numbers?

### ISSUE THREAD

**Issue by hansgru** [scriptella/scriptella-etl#11]
How to configure Scriptella CSV driver not to surround with quotes the numbers? e.g. DB IDs?

I could not find in the docs, and specifying:
```
format.id.type=number
```
seems to help when reading only, not when writing to CSV.

The same should work in fact for boolean values too.

Thank you.

**Comment by seansummers** [comment]
Does

    quote=

work for you?

How about using the text driver and quoting only the fields you need?

**Comment by hansgru** [comment]
> Does
> quote=
> work for you?

Of course not :) . I don't need **all** quotes to disappear but only the **numeric** cells :).

> How about using the text driver and quoting only the fields you need?

The text driver has no built in escapings required by CSV to be a "correct" CSV.

**Comment by ejboy** [comment]
Scriptella CSVWriter is based on opencsv project code with additional modifications. The new version of CSVWriter in opencsv allows escaping to be enabled only if a string contains special characters. I'm not available right now to merge this change, but I would happily accept a patch which incorporates new changes. History of changes: http://sourceforge.net/p/opencsv/source/ci/6dcdf8971c1dbf438191cd6080c382b47b4940bf/log/?path=/src/main/java/com/opencsv/CSVWriter.java
