### ISSUE TITLE
Fix JDK 8 Nashorn JavaScript engine integration

### ISSUE THREAD

**Issue by ejboy** [scriptella/scriptella-etl#2]
Failing test: https://gist.github.com/ejboy/00ad9d3614d66ce6749e

Once this issue fixed. Remove TODOs about this issue.

**Comment by klasker** [comment]
How would one use "nashorn_import_variables"? I don't see any references to it in the latest code.

**Comment by ejboy** [comment]
Due to Nashorn being deprecated in JDK11 (https://openjdk.java.net/jeps/335) and its incompatibilities with Scriptella, switched to Rhino (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino) with javax.script adapter. (In the long term consider using GraalVM)

As a workaround, please use the following connection declaration:
   
    <connection driver="script">
        language=rhino
    </connection>
(assuming that rhino.jar and rhino-js-engine.jar are on classpath)
